version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: node --version
      - run:
          name: Run linter
          command: yarn run lint
      - run:
          name: Run tests
          command: yarn run test
      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always
workflows:
  app-workflow:
    jobs:
      - test
